export const LEVELS_NEXT = [
  {
    id: 901,
    title: "Missing getServerSideProps",
    difficulty: "Easy",
    language: "Next.js",
    description: "Using client-side data fetching when SSR is needed.",
    buggyCode: "export default function Page() {\n  const [data, setData] = useState(null);\n  \n  useEffect(() => {\n    fetch('/api/data').then(res => res.json()).then(setData);\n  }, []);\n  \n  return <div>{data}</div>;\n}",
    fixedCode: "export async function getServerSideProps() {\n  const res = await fetch('https://api.example.com/data');\n  const data = await res.json();\n  \n  return {\n    props: { data }\n  };\n}\n\nexport default function Page({ data }) {\n  return <div>{data}</div>;\n}",
    hint: "Use getServerSideProps for server-side rendering.",
    bugLine: 1,
    explanation: "Client-side fetching causes layout shift and is not SEO friendly."
  },
  {
    id: 902,
    title: "Using window in SSR",
    difficulty: "Easy",
    language: "Next.js",
    description: "window is not defined on the server.",
    buggyCode: "export default function Page() {\n  console.log(window.location.href);\n  return <div>URL</div>;\n}",
    fixedCode: "export default function Page() {\n  if (typeof window !== 'undefined') {\n    console.log(window.location.href);\n  }\n  return <div>URL</div>;\n}",
    hint: "SSR doesn't have access to browser globals.",
    bugLine: 2,
    explanation: "window is only available in the browser."
  },
  {
    id: 903,
    title: "Wrong Link Usage",
    difficulty: "Medium",
    language: "Next.js",
    description: "Using <a> instead of Next.js Link for internal routes.",
    buggyCode: "export default function Nav() {\n  return <a href='/about'>About</a>;\n}",
    fixedCode: "import Link from 'next/link';\n\nexport default function Nav() {\n  return <Link href='/about'>About</Link>;\n}",
    hint: "Use Link component for internal navigation.",
    bugLine: 3,
    explanation: "Next.js Link enables client-side navigation and prefetch."
  },
  {
    id: 904,
    title: "getServerSideProps Not Async",
    difficulty: "Medium",
    language: "Next.js",
    description: "Data fetching function missing async keyword.",
    buggyCode: "export function getServerSideProps(context) {\n  const data = fetch('https://api.com');\n  return { props: { data } };\n}",
    fixedCode: "export async function getServerSideProps(context) {\n  const res = await fetch('https://api.com');\n  const data = await res.json();\n  return { props: { data } };\n}",
    hint: "Server-side fetching normally uses async/await.",
    bugLine: 1,
    explanation: "fetch() returns a Promise; must await and be async."
  },
  {
    id: 905,
    title: "Dynamic Route Param Misuse",
    difficulty: "Medium",
    language: "Next.js",
    description: "Accessing wrong param name from context.",
    buggyCode: "// pages/posts/[id].js\nexport async function getServerSideProps({ params }) {\n  const slug = params.slug;\n}",
    fixedCode: "// pages/posts/[id].js\nexport async function getServerSideProps({ params }) {\n  const id = params.id;\n}",
    hint: "Dynamic file name determines the param key.",
    bugLine: 3,
    explanation: "File [id].js exposes params.id, not params.slug."
  },
  {
    id: 906,
    title: "Missing return in getStaticProps",
    difficulty: "Hard",
    language: "Next.js",
    description: "Props never returned to the page.",
    buggyCode: "export async function getStaticProps() {\n  const data = await fetch('https://api.com').then(r => r.json());\n}",
    fixedCode: "export async function getStaticProps() {\n  const data = await fetch('https://api.com').then(r => r.json());\n  return { props: { data } };\n}",
    hint: "Must always return an object with props.",
    bugLine: 1,
    explanation: "No return statement meant page got no props."
  },
  {
    id: 907,
    title: "Using useRouter Outside Component",
    difficulty: "Hard",
    language: "Next.js",
    description: "Hooks must only run inside React components.",
    buggyCode: "import { useRouter } from 'next/router';\n\nconst router = useRouter();\n\nexport default function Page() {\n  return <div>Test</div>;\n}",
    fixedCode: "import { useRouter } from 'next/router';\n\nexport default function Page() {\n  const router = useRouter();\n  return <div>Test</div>;\n}",
    hint: "Hooks cannot be called at top-level module scope.",
    bugLine: 3,
    explanation: "All Hooks must run inside React function components."
  },
  {
    id: 908,
    title: "Image Optimization Wrong Domain",
    difficulty: "Hard",
    language: "Next.js",
    description: "Using external image without configuring domain.",
    buggyCode: "import Image from 'next/image';\n\nexport default function Page() {\n  return <Image src='https://example.com/img.png' width={200} height={200} />;\n}",
    fixedCode: "// next.config.js\nmodule.exports = {\n  images: {\n    domains: ['example.com'],\n  },\n};\n\n// Page\nimport Image from 'next/image';\n\nexport default function Page() {\n  return <Image src='https://example.com/img.png' width={200} height={200} />;\n}",
    hint: "External image domains must be added to Next config.",
    bugLine: 1,
    explanation: "Next.js blocks unconfigured external domains for images."
  },
  {
    id: 909,
    title: "API Route Named Incorrectly",
    difficulty: "Hard",
    language: "Next.js",
    description: "API route file not under /pages/api.",
    buggyCode: "// pages/my-api.js\nexport default function handler(req, res) {\n  res.status(200).json({ ok: true });\n}",
    fixedCode: "// pages/api/my-api.js\nexport default function handler(req, res) {\n  res.status(200).json({ ok: true });\n}",
    hint: "API routes must live in /pages/api folder.",
    bugLine: 1,
    explanation: "Next.js only treats files under pages/api as API routes."
  },
  {
    id: 910,
    title: "Incorrect Head Usage",
    difficulty: "Hard",
    language: "Next.js",
    description: "Using <head> instead of Next.js <Head>.",
    buggyCode: "export default function Page() {\n  return (\n    <>\n      <head>\n        <title>Title</title>\n      </head>\n      <div>Content</div>\n    </>\n  );\n}",
    fixedCode: "import Head from 'next/head';\n\nexport default function Page() {\n  return (\n    <>\n      <Head>\n        <title>Title</title>\n      </Head>\n      <div>Content</div>\n    </>\n  );\n}",
    hint: "Use the Head component for metadata.",
    bugLine: 3,
    explanation: "Raw <head> tags are not managed by Next.js correctly."
  },
  {
    id: 911,
    title: "Missing React Import in Pages Router",
    difficulty: "Easy",
    language: "Next.js",
    description: "Using JSX without importing React.",
    buggyCode: "export default function Home() {\n  return <h1>Welcome</h1>;\n}",
    fixedCode: "import React from 'react';\n\nexport default function Home() {\n  return <h1>Welcome</h1>;\n}",
    hint: "Some Next.js setups still need React import.",
    bugLine: 2,
    explanation: "Older JSX transforms require React in scope."
  },
  {
    id: 912,
    title: "Wrong Folder Structure",
    difficulty: "Easy",
    language: "Next.js",
    description: "Page file not in pages directory.",
    buggyCode: "// components/Home.js\nexport default function Home() {\n  return <h1>Home</h1>;\n}",
    fixedCode: "// pages/index.js\nexport default function Home() {\n  return <h1>Home</h1>;\n}",
    hint: "Page files must be in pages directory.",
    bugLine: 1,
    explanation: "Next.js only recognizes files in pages/ as routes."
  },
  {
    id: 913,
    title: "Case-Sensitive Route",
    difficulty: "Easy",
    language: "Next.js",
    description: "Using wrong case in file name.",
    buggyCode: "// pages/About.js\nexport default function About() {\n  return <h1>About</h1>;\n}",
    fixedCode: "// pages/about.js\nexport default function About() {\n  return <h1>About</h1>;\n}",
    hint: "Page routes are usually lowercase.",
    bugLine: 1,
    explanation: "File name case affects the URL route."
  },
  {
    id: 914,
    title: "Missing Layout Component",
    difficulty: "Easy",
    language: "Next.js",
    description: "No root layout in App Router.",
    buggyCode: "// app/page.js\nexport default function Home() {\n  return <h1>Home</h1>;\n}",
    fixedCode: "// app/layout.js\nexport default function RootLayout({ children }) {\n  return (\n    <html lang='en'>\n      <body>{children}</body>\n    </html>\n  );\n}\n\n// app/page.js\nexport default function Home() {\n  return <h1>Home</h1>;\n}",
    hint: "App Router requires root layout.",
    bugLine: 1,
    explanation: "Every app must have a root layout with html and body tags."
  },
  {
    id: 915,
    title: "Incorrect Image Import",
    difficulty: "Easy",
    language: "Next.js",
    description: "Using wrong import for Image component.",
    buggyCode: "import Image from 'next/image';\n\nexport default function Page() {\n  return (\n    <img src='/photo.jpg' alt='Photo' />\n  );\n}",
    fixedCode: "import Image from 'next/image';\n\nexport default function Page() {\n  return (\n    <Image src='/photo.jpg' alt='Photo' width={500} height={300} />\n  );\n}",
    hint: "Use Next.js Image component for optimization.",
    bugLine: 6,
    explanation: "Regular img tag doesn't get Next.js optimizations."
  },
  {
    id: 916,
    title: "Static Asset Path Wrong",
    difficulty: "Easy",
    language: "Next.js",
    description: "Incorrect path to public files.",
    buggyCode: "import Image from 'next/image';\n\nexport default function Page() {\n  return (\n    <Image src='/public/logo.png' alt='Logo' width={100} height={100} />\n  );\n}",
    fixedCode: "import Image from 'next/image';\n\nexport default function Page() {\n  return (\n    <Image src='/logo.png' alt='Logo' width={100} height={100} />\n  );\n}",
    hint: "Public files don't include /public in path.",
    bugLine: 5,
    explanation: "Files in public/ are served from root path."
  },
  {
    id: 917,
    title: "Missing Head Title",
    difficulty: "Easy",
    language: "Next.js",
    description: "Page without proper metadata.",
    buggyCode: "export default function Page() {\n  return <div>Content</div>;\n}",
    fixedCode: "import Head from 'next/head';\n\nexport default function Page() {\n  return (\n    <>\n      <Head>\n        <title>My Page</title>\n      </Head>\n      <div>Content</div>\n    </>\n  );\n}",
    hint: "Every page should have a title.",
    bugLine: 1,
    explanation: "Missing page title affects SEO and user experience."
  },
  {
    id: 918,
    title: "Wrong Script Component Usage",
    difficulty: "Easy",
    language: "Next.js",
    description: "Using script tag instead of Next.js Script.",
    buggyCode: "export default function Page() {\n  return (\n    <div>\n      <script src='/analytics.js' />\n      <div>Content</div>\n    </div>\n  );\n}",
    fixedCode: "import Script from 'next/script';\n\nexport default function Page() {\n  return (\n    <div>\n      <Script src='/analytics.js' strategy='afterInteractive' />\n      <div>Content</div>\n    </div>\n  );\n}",
    hint: "Use Script component for better performance.",
    bugLine: 4,
    explanation: "Next.js Script component optimizes loading strategy."
  },
  {
    id: 919,
    title: "Missing Error Boundary",
    difficulty: "Easy",
    language: "Next.js",
    description: "Page without error handling.",
    buggyCode: "export default function Page({ data }) {\n  return <div>{data.items[0].name}</div>;\n}",
    fixedCode: "export default function Page({ data }) {\n  if (!data || !data.items || data.items.length === 0) {\n    return <div>No data available</div>;\n  }\n  return <div>{data.items[0].name}</div>;\n}",
    hint: "Always check for null/undefined.",
    bugLine: 2,
    explanation: "Accessing nested properties without checks causes errors."
  },
  {
    id: 920,
    title: "Incorrect CSS Import",
    difficulty: "Easy",
    language: "Next.js",
    description: "Wrong way to import CSS modules.",
    buggyCode: "import './styles.css';\n\nexport default function Page() {\n  return <div className='container'>Content</div>;\n}",
    fixedCode: "import styles from './styles.module.css';\n\nexport default function Page() {\n  return <div className={styles.container}>Content</div>;\n}",
    hint: "Use CSS modules for scoped styling.",
    bugLine: 1,
    explanation: "Global CSS imports can cause style conflicts."
  },
  {
    id: 921,
    title: "getStaticPaths Missing",
    difficulty: "Medium",
    language: "Next.js",
    description: "Dynamic page without getStaticPaths.",
    buggyCode: "// pages/posts/[id].js\nexport async function getStaticProps({ params }) {\n  // fetch post\n}",
    fixedCode: "// pages/posts/[id].js\nexport async function getStaticPaths() {\n  return {\n    paths: [],\n    fallback: true,\n  };\n}\n\nexport async function getStaticProps({ params }) {\n  // fetch post\n}",
    hint: "Static dynamic pages need getStaticPaths.",
    bugLine: 1,
    explanation: "getStaticProps on dynamic routes requires getStaticPaths."
  },
  {
    id: 922,
    title: "Middleware Wrong Export",
    difficulty: "Medium",
    language: "Next.js",
    description: "Middleware not using correct function name.",
    buggyCode: "// middleware.js\nexport default function myMiddleware(req) {\n  // middleware logic\n}",
    fixedCode: "// middleware.js\nimport { NextResponse } from 'next/server';\n\nexport function middleware(req) {\n  return NextResponse.next();\n}",
    hint: "Middleware exports must be named 'middleware'.",
    bugLine: 2,
    explanation: "Next.js looks for a function named 'middleware'."
  },
  {
    id: 923,
    title: "API Route Missing Method Check",
    difficulty: "Medium",
    language: "Next.js",
    description: "Not checking HTTP method in API route.",
    buggyCode: "// pages/api/users.js\nexport default function handler(req, res) {\n  const data = req.body;\n  res.status(200).json(data);\n}",
    fixedCode: "// pages/api/users.js\nexport default function handler(req, res) {\n  if (req.method === 'POST') {\n    const data = req.body;\n    res.status(200).json(data);\n  } else {\n    res.status(405).json({ error: 'Method not allowed' });\n  }\n}",
    hint: "Always check request method in API routes.",
    bugLine: 3,
    explanation: "Without method check, all requests are processed."
  },
  {
    id: 924,
    title: "Missing ISR Revalidation",
    difficulty: "Medium",
    language: "Next.js",
    description: "Static page never updates.",
    buggyCode: "export async function getStaticProps() {\n  const data = await fetch('https://api.com/posts');\n  return {\n    props: { posts: data }\n  };\n}",
    fixedCode: "export async function getStaticProps() {\n  const data = await fetch('https://api.com/posts');\n  return {\n    props: { posts: data },\n    revalidate: 60, // revalidate every 60 seconds\n  };\n}",
    hint: "Add revalidate for incremental static regeneration.",
    bugLine: 1,
    explanation: "Without revalidate, page stays stale forever."
  },
  {
    id: 925,
    title: "Client-Side Data Fetching in Component",
    difficulty: "Medium",
    language: "Next.js",
    description: "Fetching data during render causes issues.",
    buggyCode: "export default function Page() {\n  const [data, setData] = useState(null);\n  \n  fetch('/api/data')\n    .then(res => res.json())\n    .then(setData);\n  \n  return <div>{data?.message}</div>;\n}",
    fixedCode: "import { useEffect } from 'react';\n\nexport default function Page() {\n  const [data, setData] = useState(null);\n  \n  useEffect(() => {\n    fetch('/api/data')\n      .then(res => res.json())\n      .then(setData);\n  }, []);\n  \n  return <div>{data?.message}</div>;\n}",
    hint: "Data fetching should be in useEffect.",
    bugLine: 5,
    explanation: "Fetching during render causes infinite loops."
  },
  {
    id: 926,
    title: "Wrong Environment Variable Usage",
    difficulty: "Medium",
    language: "Next.js",
    description: "Client-side access to server-only env vars.",
    buggyCode: "export default function Page() {\n  return <div>API Key: {process.env.API_KEY}</div>;\n}",
    fixedCode: "export default function Page() {\n  return <div>API Key: {process.env.NEXT_PUBLIC_API_KEY}</div>;\n}",
    hint: "Client-side env vars need NEXT_PUBLIC_ prefix.",
    bugLine: 2,
    explanation: "Regular env vars are only available server-side."
  },
  {
    id: 927,
    title: "Missing Error Handling in API Route",
    difficulty: "Medium",
    language: "Next.js",
    description: "API route crashes on error.",
    buggyCode: "export default async function handler(req, res) {\n  const data = await fetch('https://api.com');\n  const json = await data.json();\n  res.status(200).json(json);\n}",
    fixedCode: "export default async function handler(req, res) {\n  try {\n    const data = await fetch('https://api.com');\n    const json = await data.json();\n    res.status(200).json(json);\n  } catch (error) {\n    res.status(500).json({ error: 'Failed to fetch' });\n  }\n}",
    hint: "Wrap API routes in try-catch.",
    bugLine: 1,
    explanation: "Unhandled errors crash the API route."
  },
  {
    id: 928,
    title: "Image Without Required Props",
    difficulty: "Medium",
    language: "Next.js",
    description: "Missing width/height on Image component.",
    buggyCode: "import Image from 'next/image';\n\nexport default function Page() {\n  return <Image src='/photo.jpg' alt='Photo' />;\n}",
    fixedCode: "import Image from 'next/image';\n\nexport default function Page() {\n  return (\n    <Image \n      src='/photo.jpg' \n      alt='Photo' \n      width={500}\n      height={300}\n    />\n  );\n}",
    hint: "Next.js Image requires dimensions.",
    bugLine: 4,
    explanation: "Image component needs width and height for optimization."
  },
  {
    id: 929,
    title: "Missing Cache Control",
    difficulty: "Medium",
    language: "Next.js",
    description: "API responses not cached.",
    buggyCode: "export default function handler(req, res) {\n  res.status(200).json({ data: 'value' });\n}",
    fixedCode: "export default function handler(req, res) {\n  res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate');\n  res.status(200).json({ data: 'value' });\n}",
    hint: "Add cache headers for better performance.",
    bugLine: 2,
    explanation: "Without cache headers, responses are not cached."
  },
  {
    id: 930,
    title: "Incorrect Dynamic Import",
    difficulty: "Medium",
    language: "Next.js",
    description: "Wrong syntax for dynamic import.",
    buggyCode: "import dynamic from 'next/dynamic';\n\nconst HeavyComponent = dynamic(() => './HeavyComponent');",
    fixedCode: "import dynamic from 'next/dynamic';\n\nconst HeavyComponent = dynamic(() => import('./HeavyComponent'));",
    hint: "Dynamic import needs import() function.",
    bugLine: 3,
    explanation: "Wrong syntax - should use import() not string path."
  },
  {
    id: 931,
    title: "Server Action Missing 'use server'",
    difficulty: "Hard",
    language: "Next.js",
    description: "Server component action without directive.",
    buggyCode: "// app/actions.js\nexport async function createPost(data) {\n  // save to database\n}",
    fixedCode: "// app/actions.js\n'use server';\n\nexport async function createPost(data) {\n  // save to database\n}",
    hint: "Server actions need 'use server' directive.",
    bugLine: 2,
    explanation: "Without 'use server', function runs on client."
  },
  {
    id: 932,
    title: "Missing Suspense Boundary",
    difficulty: "Hard",
    language: "Next.js",
    description: "Streaming without Suspense wrapper.",
    buggyCode: "// app/page.js\nimport { getData } from './lib/data';\n\nexport default async function Page() {\n  const data = await getData();\n  return <div>{data}</div>;\n}",
    fixedCode: "// app/page.js\nimport { Suspense } from 'react';\nimport { getData } from './lib/data';\n\nasync function DataComponent() {\n  const data = await getData();\n  return <div>{data}</div>;\n}\n\nexport default function Page() {\n  return (\n    <Suspense fallback={<div>Loading...</div>}>\n      <DataComponent />\n    </Suspense>\n  );\n}",
    hint: "Async components need Suspense in App Router.",
    bugLine: 4,
    explanation: "Async components without Suspense block the whole page."
  },
  {
    id: 933,
    title: "Wrong Middleware Matcher",
    difficulty: "Hard",
    language: "Next.js",
    description: "Middleware running on all routes.",
    buggyCode: "// middleware.js\nexport function middleware(req) {\n  // runs on every request\n}",
    fixedCode: "// middleware.js\nimport { NextResponse } from 'next/server';\n\nexport function middleware(req) {\n  // middleware logic\n}\n\nexport const config = {\n  matcher: '/dashboard/:path*',\n};",
    hint: "Use matcher config to limit middleware scope.",
    bugLine: 1,
    explanation: "Without matcher, middleware runs on all pages."
  },
  {
    id: 934,
    title: "Missing SWR Configuration",
    difficulty: "Hard",
    language: "Next.js",
    description: "SWR without proper config leads to infinite requests.",
    buggyCode: "import useSWR from 'swr';\n\nfunction Profile() {\n  const { data } = useSWR('/api/user');\n  return <div>{data?.name}</div>;\n}",
    fixedCode: "import useSWR from 'swr';\n\nconst fetcher = (url) => fetch(url).then(res => res.json());\n\nfunction Profile() {\n  const { data } = useSWR('/api/user', fetcher);\n  return <div>{data?.name}</div>;\n}",
    hint: "SWR needs a fetcher function.",
    bugLine: 4,
    explanation: "Without fetcher, SWR doesn't know how to fetch data."
  },
  {
    id: 935,
    title: "ISR with Dynamic Data",
    difficulty: "Hard",
    language: "Next.js",
    description: "getStaticPaths with dynamic data needs fallback.",
    buggyCode: "export async function getStaticPaths() {\n  const posts = await getAllPosts();\n  const paths = posts.map(post => ({\n    params: { id: post.id.toString() }\n  }));\n  return { paths };\n}",
    fixedCode: "export async function getStaticPaths() {\n  const posts = await getAllPosts();\n  const paths = posts.map(post => ({\n    params: { id: post.id.toString() }\n  }));\n  return {\n    paths,\n    fallback: 'blocking', // or true\n  };\n}",
    hint: "Use fallback for dynamic ISR.",
    bugLine: 7,
    explanation: "Without fallback, new pages return 404."
  },
  {
    id: 936,
    title: "Missing CORS Headers in API",
    difficulty: "Hard",
    language: "Next.js",
    description: "API route blocks cross-origin requests.",
    buggyCode: "export default function handler(req, res) {\n  res.status(200).json({ data: 'value' });\n}",
    fixedCode: "export default function handler(req, res) {\n  res.setHeader('Access-Control-Allow-Origin', '*');\n  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');\n  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');\n  \n  if (req.method === 'OPTIONS') {\n    return res.status(200).end();\n  }\n  \n  res.status(200).json({ data: 'value' });\n}",
    hint: "API routes need CORS headers for external access.",
    bugLine: 2,
    explanation: "Without CORS headers, browsers block cross-origin requests."
  },
  {
    id: 937,
    title: "Wrong Cache Strategy for Script",
    difficulty: "Hard",
    language: "Next.js",
    description: "Script loading blocks page.",
    buggyCode: "import Script from 'next/script';\n\nexport default function Page() {\n  return (\n    <Script src='/analytics.js' />\n  );\n}",
    fixedCode: "import Script from 'next/script';\n\nexport default function Page() {\n  return (\n    <Script \n      src='/analytics.js' \n      strategy='afterInteractive' \n      onLoad={() => console.log('loaded')}\n    />\n  );\n}",
    hint: "Choose appropriate script loading strategy.",
    bugLine: 6,
    explanation: "Without strategy, scripts can block page rendering."
  },
  {
    id: 938,
    title: "Middleware Infinite Redirect",
    difficulty: "Hard",
    language: "Next.js",
    description: "Redirect loop in middleware.",
    buggyCode: "export function middleware(req) {\n  if (!req.cookies.token) {\n    return NextResponse.redirect('/login');\n  }\n}",
    fixedCode: "export function middleware(req) {\n  if (!req.cookies.token && !req.nextUrl.pathname.startsWith('/login')) {\n    return NextResponse.redirect('/login');\n  }\n}",
    hint: "Check current path before redirecting.",
    bugLine: 3,
    explanation: "Without path check, redirects to /login infinitely."
  },
  {
    id: 939,
    title: "Missing Edge Runtime Config",
    difficulty: "Hard",
    language: "Next.js",
    description: "API route trying to use Node.js APIs on Edge.",
    buggyCode: "export const config = {\n  runtime: 'edge',\n};\n\nexport default function handler(req) {\n  const fs = require('fs'); // Won't work on Edge\n  // ...\n}",
    fixedCode: "export const config = {\n  runtime: 'edge',\n};\n\nexport default function handler(req) {\n  // Use Edge-compatible APIs only\n  return new Response('Hello Edge');\n}",
    hint: "Edge runtime doesn't support all Node.js APIs.",
    bugLine: 6,
    explanation: "fs module not available in Edge Runtime."
  },
  {
    id: 940,
    title: "Parallel Data Fetching Race Condition",
    difficulty: "Hard",
    language: "Next.js",
    description: "Multiple fetches without proper synchronization.",
    buggyCode: "export default async function Page() {\n  const user = await getUser();\n  const posts = await getUserPosts(user.id);\n  const comments = await getPostComments(posts[0].id);\n  \n  return <div>...</div>;\n}",
    fixedCode: "export default async function Page() {\n  const [user, posts, comments] = await Promise.all([\n    getUser(),\n    getUserPosts(),\n    getPostComments()\n  ]);\n  \n  return <div>...</div>;\n}",
    hint: "Use Promise.all for parallel fetching.",
    bugLine: 3,
    explanation: "Sequential fetching slows down page load; fetch in parallel."
  }
];